services:
  - type: web
    name: nexus-chat-api
    env: node
    buildCommand: npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
